### ISSUE TITLE
bug: tab characters not rendered correctly

### ISSUE THREAD

**Issue by crackcomm** [arxanas/scm-record#2]
Issue mentioned on discord. Not sure exactly what happened - not rendered tab or replaced with a different character.

![image](https://github.com/arxanas/scm-record/assets/206368/b1345d4b-ff7a-4c6d-ae53-1232bf84e8f0)

misrendered output (notice last character is missing):
![image](https://github.com/arxanas/scm-record/assets/206368/87a33fa6-b6df-4d7e-ae63-66feb2d3e3b1)

with spaces instead of tabs:
![image](https://github.com/arxanas/scm-record/assets/206368/9fe7232a-ebed-4634-a1d5-6ba371231788)

**Comment by crackcomm** [comment]
I noticed missing last characters even in output w/o indentation. It was some `go.sum` file IIRC.

**Comment by arxanas** [comment]
> Also running into this this. I couldn't quite deduce in the code where this is rendered/handled (I did look through src/render.rs).

@firestack I believe that there's nowhere specific in the code that handles tab characters. My guess is that we simply print tab characters to the screen literally, and the terminal emulator does the normal tab behavior, i.e. moves the cursor to the next tabbable column, and continues printing there. This kind of makes sense as we see in the screenshots how random parts of the output seem to be truncated — it would make sense if we just started drawing/overwriting at random later portions of the line.

The easiest fix would be to replace each tab character with several spaces (note that we *have* to choose a fixed-width representation as we won't be able to calculate where the rest of the line would render, figure out where to truncate text, be able to render text side-by-side, etc.).

- The main implementation problem is figuring out *where* to do the substitution, as it might affect the calculation of widths used elsewhere.
- Using whitespace has the problem that you can't tell the difference between a tab character and other whitespace just from the UI, although it's probably fine.
- The ideal fix might involve rendering tabs (and other control characters!) with differently-colored icons.
  - We do this currently for newlines (which you can see in the original screenshots): https://github.com/arxanas/scm-record/blob/0bf05a238996209a0aa751606088bcb8a8938072/src/ui.rs#L3031
  - Here's some visible Unicode control character symbols that we could consider substituting for various invisible counterparts: https://www.compart.com/en/unicode/block/U+2400
  - For tab in particular, we could use [␉](https://www.compart.com/en/unicode/U+2409), but most users probably won't know what that means. For the same reason, I chose to use [⏎](https://www.compart.com/en/unicode/U+23CE) instead of [␤](https://www.compart.com/en/unicode/U+2424).
    - There might be ideas here: https://ux.stackexchange.com/questions/91255/how-can-i-best-display-a-blank-space-character

**Comment by arxanas** [comment]
The arrow seems fine to me. I would prefer to have intuitive iconography to descriptive iconography. We are not trying to have 100% fidelity for the rendered diff anyways. But I would like to see the arrow embedded in some number of spaces for alignment, rather than having the tab itself span only one column.
